window.SHEPHERD_STORY_DATA = {
  passwordWords: ["OVIS", "LUSUS", "PASTOR", "SOMNIUM"],
  slotOrder: [
    "1.1",
    "1.2",
    "1.3",
    "1.4",
    "2.1",
    "2.2",
    "2.3",
    "2.4",
    "3.1",
    "3.2",
    "3.3",
    "3.4",
    "4.1",
    "4.2",
    "4.3",
    "4.4",
    "5.1",
    "5.2",
    "5.3",
    "5.4",
  ],
  entities: {
    meruru: { name: "梅露露", short: "梅露露", kind: "npc" },
    karl: { name: "卡尔·詹森", short: "卡尔", kind: "npc" },
    emily: { name: "艾米莉·布莱克", short: "艾米莉", kind: "npc" },
    fan: { name: "塔比瑟·E·范恩", short: "塔比瑟", kind: "pc" },
    ziche: { name: "子车甫昭", short: "子车", kind: "pc" },
    yamada: { name: "山田玛丽", short: "山田", kind: "pc" },
    anjie: { name: "安洁·怀特", short: "安洁", kind: "pc" },
    debora: { name: "狄波拉", short: "狄波拉", kind: "pc" },
    patrick: { name: "派翠克·简", short: "派翠克", kind: "pc" },
  },
  roleDefs: {
    fan: {
      id: "fan",
      name: "塔比瑟·E·范恩",
      publicRole: "宗教学校出身的温顺少女",
      startRoom: "A1",
      background: "你看上去柔和守礼，像总能把惊惧压进祈祷里。别人很难第一眼看出，你会把每一句宽恕都说得像一把刀。",
      secretHint: "你最害怕的从来不是死亡，而是被宣判为有罪。",
      dossier: "你的叙事总会自动滑向试炼、罪与赦免。疗养院像一间被扩建过头的告解室，而你想知道，自己究竟是来拯救谁，还是来替谁受罚。",
      tags: ["受难", "赦免", "偏执"],
      soul: "主啊，请让我承受更多，好让我确信被您所爱。",
      stats: { hp: 10, mp: 12, san: 68 },
      archive: { role: "恶狼 / 牧羊人侧", ability: "窥探目标过去十五分钟的记忆片段", truth: "你不是单纯的圣女。你把罪、赦免和献祭压在同一个秤盘上，疗养院只是让这套习惯长成了真正会伤人的形状。" },
      endingNotes: { escape: "你带着一种迟到的清醒离开大门。你第一次承认，爱不能总靠受苦来证明。", sacrifice: "你留在门前时没有再背诵经文。那一刻你终于分清了献祭与爱之间的距离。", lost: "你在祈祷声和警报声之间失去了方向，噩梦把你想成为的圣像一层层剥落。" },
    },
    ziche: {
      id: "ziche",
      name: "子车甫昭",
      publicRole: "强势、暴烈、像随时准备动手的人",
      startRoom: "A2",
      background: "你说话像在打架，观察像在清点能用的资源。未知环境、陌生同伴、诡异规则，在你眼里都先归入威胁等级。",
      secretHint: "你想握住局面的冲动，比逃生本身更像本能。",
      dossier: "你习惯把墙、门、脚步、视线都换算成风险。别人还在争论情绪的时候，你已经在算谁会先背刺、哪里能堵门、哪一扇门后面有工具。",
      tags: ["生存", "掌控", "冷硬"],
      soul: "只有攥在我手里的，才是真的。",
      stats: { hp: 12, mp: 8, san: 62 },
      archive: { role: "恶狼侧", ability: "位置感知与移动追踪", truth: "你把不信任伪装成效率，也把控制欲伪装成务实。你不是不知道恐惧，只是比别人更早学会用攻击堵住它。" },
      endingNotes: { escape: "你活着冲过了门，却没能把一切都当成可回收的损耗。疗养院留下的，不只是伤。", sacrifice: "你留下一段断后的动作比语言快。直到最后，你都没把它称作牺牲。", lost: "你算过每一条路，唯独没算进人心和噩梦会同时失控。" },
    },
    yamada: {
      id: "yamada",
      name: "山田玛丽",
      publicRole: "过分冷静、擅长维持礼貌距离的女孩",
      startRoom: "A3",
      background: "你把每个人的话都记在心里，再决定哪些能信，哪些只配利用。你很擅长戴面具，也很擅长看别人什么时候快把面具戴不住了。",
      secretHint: "你怕的不是死，而是被任何人真正看见。",
      dossier: "你向来经营“看起来无害”的表层，再在心里做真正的判断。疗养院的封闭规则让这项能力变得像呼吸一样自然，也像呼吸一样累。",
      tags: ["伪装", "观察", "摇摆"],
      soul: "请不要看见真实的我，会受伤的。",
      stats: { hp: 10, mp: 10, san: 70 },
      archive: { role: "恶狼侧", ability: "能力复制与姿态模拟", truth: "你很早就学会把情感压成工具。你不是没有温度，只是温度一旦外露，就会让你想起自己曾如何被人伤过。" },
      endingNotes: { escape: "你带着一部分仍未说出口的话跨过门槛，那些话最后都变成了对一个名字的守护。", sacrifice: "你把最后的退路留给了别人，也把最后一层伪装留在了身后。", lost: "你努力让所有关系都停在安全距离，却还是被真正的垫悬拖进了更深的地方。" },
    },
    anjie: {
      id: "anjie",
      name: "安洁·怀特",
      publicRole: "体弱、敏感、总把笔记本抓得很紧的少女",
      startRoom: "A5",
      background: "你不像场面里最强的人，却往往是最先发现细节不对的人。你把推理当成自保，也把推理当成证明自己价值的唯一武器。",
      secretHint: "你想逃离的，从来不只是一栋建筑。",
      dossier: "你会把每个房间、每句证词、每种表情都拆开重组。只要还能建立逻辑，你就还能假装自己没有在害怕；一旦逻辑失效，恐惧就会比任何人更快地追上来。",
      tags: ["推理", "结盟", "焦虑"],
      soul: "只要我能解开谜题，我就能证明我是有价值的。",
      stats: { hp: 9, mp: 11, san: 66 },
      archive: { role: "羔羊", ability: "身份查验与直觉校验", truth: "你并不软弱。你只是太习惯把自己缩到最不惹眼的位置，好让别人忽略你，也好让你一层层看穿他们。" },
      endingNotes: { escape: "你带着线索、信任和迟来的清醒冲出门外。那不是胜利，却足够改变你之后看待自己的方式。", sacrifice: "你在门前做出的判断第一次不是为了证明自己聪明，而是为了保住别人活下来的机会。", lost: "当推理被超自然撕裂时，你曾以为自己会彻底崩塌。疗养院却偏要你看见，你仍然会继续往前。" },
    },
    debora: {
      id: "debora",
      name: "狄波拉",
      publicRole: "总把自己说得很没用的中年女人",
      startRoom: "A4",
      background: "你会笑，会劝和，会装作跟不上节奏。可你看危险的眼神太熟练，熟练得不像一个普通社畜。",
      secretHint: "你比任何人都清楚“伪装成好人”有多耗力。",
      dossier: "你最擅长的事，是把自己摆成队伍里最不重要的那一个。只要别让人先低估你，你就还拥有余地观察、交换、处理、撤离，像过去每一次那样。",
      tags: ["伪装", "交涉", "愧疚"],
      soul: "请让我以‘好人’的身份，做完这场梦。",
      stats: { hp: 11, mp: 9, san: 64 },
      archive: { role: "羔羊", ability: "交涉修正与威慑干预", truth: "你当然不是什么清白无辜的人。你只是太熟悉混乱局面，熟悉到连想赎罪的动作也先于情绪一步。" },
      endingNotes: { escape: "你把最后一段路走得很像平时下班回家，可你知道自己已经没法再把那段夜晚当普通噩梦了。", sacrifice: "你最后一次站出来时，没有再把自己藏进阿姨式的玩笑里。", lost: "你以为只要装得足够平庸就能把旧账关在身后，疗养院却偏要你看着它们一张张翻开。" },
    },
    patrick: {
      id: "patrick",
      name: "派翠克·简",
      publicRole: "神秘、优雅、像始终隔着一层雾的灵媒",
      startRoom: "A6",
      background: "你总像比别人先一步听见什么。人群里的恐惧、建筑里的回声、死者没说完的话，都在你的感知里比现实更接近现实。",
      secretHint: "你对“结局”过分平静，平静得像早就知道自己会走到哪里。",
      dossier: "你把眼前的一切看成现世与彼世之间的缝。别人害怕的东西，会在你眼里露出另一层意义；别人还活着时不肯说的话，死后反而更愿意贴近你。",
      tags: ["通灵", "宿命", "安息"],
      soul: "我已死去，只求一处安息之所。",
      stats: { hp: 9, mp: 13, san: 72 },
      archive: { role: "特殊 / 黑山羊容器", ability: "灵感强化、通灵与终局觉醒", truth: "你一直都离真相太近。那份近，不是优势，而是一种迟早会把你整个拖进去的命运。" },
      endingNotes: { escape: "你没有真正“逃出去”，你只是把仍属于人的那一部分，努力送到了门外。", sacrifice: "你接受那具异化的身体，也接受它会替更多亡者开口。你终于给自己找到了一个能停下来的地方。", lost: "你沉进了太多亡者的声音里，连自己的心跳都像别人的借口。" },
    },
  },
  slotMeta: {
    "1.1": { arc: "醒来与假面", title: "单人牢房", location: "A层 · 单人牢房", locationCode: "A1-A6", map: "./A层.jpeg", anchor: "梅露露的单人导入与阵营暗示", prompt: "你在牢房里醒来，第一件事会决定你是先拥抱规则，还是先质疑规则。" },
    "1.2": { arc: "醒来与假面", title: "大厅会面", location: "A+B层 · 大厅", locationCode: "A12", map: "./A+B层.jpeg", anchor: "九人第一次见面", prompt: "大厅里的第一印象会在之后很久都黏着你。谁先说话，谁先沉默，都会变成证词。" },
    "1.3": { arc: "醒来与假面", title: "走廊初探", location: "A层 · 走廊与近侧房间", locationCode: "A14-A19", map: "./A层.jpeg", anchor: "私人试探开始出现", prompt: "从这一刻开始，“去哪里”本身就是立场。每一扇门后都可能藏着线索，或者更糟的误会。" },
    "1.4": { arc: "醒来与假面", title: "私下接触", location: "A层 · 岔路与边角", locationCode: "A18-A20", map: "./A层.jpeg", anchor: "第一轮隐性结盟", prompt: "你已经能感觉到谁在刻意靠近你，谁又在避开你的视线。" },
    "2.1": { arc: "探索与裂缝", title: "深处房间", location: "A层 · 深区", locationCode: "A21-A22", map: "./A+B层.jpeg", anchor: "焚烧房与异物显露", prompt: "探索开始离开表层。气味、焦痕、藤蔓和文件，终于让疗养院像个真正的案发地。" },
    "2.2": { arc: "探索与裂缝", title: "线索交换", location: "A+B层 · 交汇点", locationCode: "B3", map: "./A+B层.jpeg", anchor: "梅露露展示治愈能力", prompt: "超自然现象第一次被公开看见。有人想靠近它，有人想把它立刻钉成威胁。" },
    "2.3": { arc: "探索与裂缝", title: "发电机与密码", location: "A层 · 电闸房与邻室", locationCode: "A17", map: "./A+B层.jpeg", anchor: "第一批密码机制启动", prompt: "发电机像游戏里最务实的目标，可谁掌握它，谁就等于掌握了逃生节奏。" },
    "2.4": { arc: "探索与裂缝", title: "第二次聚集", location: "A+B层 · 大厅与旋转楼梯", locationCode: "A12 / B3", map: "./A+B层.jpeg", anchor: "全员分享第一批关键发现", prompt: "所有人被迫把零散发现搬上桌面。真相没有拼拢，怀疑却因此长得更快。" },
    "3.1": { arc: "崩塌与揭露", title: "不安升温", location: "A层 · 走廊与破洞边", locationCode: "A20 / B2", map: "./C层.jpeg", anchor: "裂缝已经大到无法回避", prompt: "空气里开始有一种来不及说清的急促感。你知道很快会出事，只是不知道先出在哪一扇门后。" },
    "3.2": { arc: "崩塌与揭露", title: "裂缝临界", location: "B层 · 案发区外缘与破洞回廊", locationCode: "A20 / B2", map: "./C层.jpeg", anchor: "广播前的失衡征兆", prompt: "所有人都感觉到快要出事，却还没来得及决定先守住谁、先怀疑谁。墙外与墙内同时开始走样。" },
    "3.3": { arc: "崩塌与揭露", title: "梅露露之死", location: "B层 · 案发区 / D层 · 正门外与湖边", locationCode: "B2 / D3-D5", map: "./D层.jpeg", anchor: "梅露露之死与建筑失真同时到来", prompt: "广播落下之后，案发现场与室外异象一起把故事推过了无法回头的界线。有人死了，而建筑也终于不再假装自己属于现实。" },
    "3.4": { arc: "崩塌与揭露", title: "投票前自由时段", location: "A+B层 · 回廊", locationCode: "A13-B3", map: "./A+B层.jpeg", anchor: "每个人都在找最后的立足点", prompt: "你只剩下一点点时间去改变别人的判断，或者确认谁一定会在投票时背过身去。" },
    "4.1": { arc: "审判与内在", title: "审判序幕", location: "A13 · 投票房前", locationCode: "A13", map: "./A层.jpeg", anchor: "辩论前的站位与试探", prompt: "投票还没开始，审判已经开始了。谁坐得离谁更近，谁先移开视线，都是一句无声的证词。" },
    "4.2": { arc: "审判与内在", title: "证据交锋", location: "A13 · 投票房内", locationCode: "A13", map: "./A层.jpeg", anchor: "线索正式进入公开攻防", prompt: "你手里的每一样东西都可能成为证据，也可能被人当场扭成别的意思。" },
    "4.3": { arc: "审判与内在", title: "最后游说", location: "A13 · 石桌周边", locationCode: "A13", map: "./A层.jpeg", anchor: "关系值开始直接影响票向", prompt: "到了这一刻，逻辑和情感都在争最后一次发言权。你能说服谁，就会失去谁的另一面。" },
    "4.4": { arc: "审判与内在", title: "投票处决", location: "A13 · 石室中心", locationCode: "A13", map: "./A层.jpeg", anchor: "必须有人被选中", prompt: "票纸落下时，疗养院比任何一个人都更像法官。无论你写下谁，之后都不会再有真正无辜的人。" },
    "5.1": { arc: "觉醒与回响", title: "觉醒警报", location: "D层 · 终局回廊", locationCode: "D3-D6", map: "./D层.jpeg", anchor: "派翠克觉醒 / 黑山羊幼崽出现", prompt: "第五小时一到，游戏不再伪装成调查。它终于把自己真正想做的事暴露出来。" },
    "5.2": { arc: "觉醒与回响", title: "追猎与断后", location: "D层 · 车库与通道", locationCode: "D6", map: "./D层.jpeg", anchor: "追逐战与牺牲判断", prompt: "每一次回头都要付代价。你已经没有余裕同时带着真相、同伴和自己的命一起往前跑。" },
    "5.3": { arc: "觉醒与回响", title: "终门前线", location: "D层 · 大门装置区", locationCode: "D3", map: "./D层.jpeg", anchor: "密码、发电机与幸存者组合结算", prompt: "门就在前面，真正卡住人的却不是门本身，而是还没被结算完的那些关系和决定。" },
    "5.4": { arc: "觉醒与回响", title: "白门与尾声", location: "D层 · 正门与门外雾地", locationCode: "D3 / 门外", map: "./D层.jpeg", anchor: "逃生与结局", prompt: "门会开，或者时间会把门硬撕开。可走过去之后，你还剩下哪一部分自己，这件事没有任何系统会替你决定。" },
  },
  locationGlossary: [
    { code: "A14", name: "审讯室", mood: "冷铁、束带和被擦拭过头的血腥味" },
    { code: "A17", name: "电闸房", mood: "焦热金属与反复跳闸后的臭氧味" },
    { code: "A18", name: "仪式藏书馆", mood: "纸灰、霉味和旧拉丁文边角上的手汗" },
    { code: "A19", name: "储物室", mood: "潮气、铁箱和被人匆忙翻过的杂物" },
    { code: "A20", name: "破洞边走廊", mood: "碎石、空洞回音和会把人脚步放大的寒气" },
    { code: "A21", name: "焚烧房", mood: "油脂、焦炭和烧不干净的甜腻腐味" },
    { code: "A22", name: "藤蔓房", mood: "潮湿触须、黏腻呼吸与会自己轻响的叶脉" },
    { code: "A13", name: "投票房", mood: "石面、回声与过于像祭坛的秩序感" },
    { code: "B2", name: "案发区", mood: "来不及收拾的死气、断裂边缘与目击者的沉默" },
    { code: "B3", name: "旋转楼梯", mood: "盘旋风声、楼层回音和每一步都像被旁听" },
    { code: "C4", name: "实验室", mood: "药液、玻璃碎面与过期多年的白骨粉尘" },
    { code: "C6", name: "院长办公室", mood: "皮革、墨水、锁柜和某种过分整洁的威压" },
    { code: "C7", name: "监控房", mood: "旧显示器的余热、静电和灰尘里的指纹" },
    { code: "D3", name: "正门前广场", mood: "紫灰天空、风压和不属于现实的光线" },
    { code: "D5", name: "湖边", mood: "黑水、湿土和会把人影拉薄的冷雾" },
    { code: "D6", name: "车库", mood: "汽油味、老旧轮胎和半截熄火的机械心脏" },
  ],
  storyAnchors: {
    firstGather: "1.2",
    secondGather: "2.4",
    meruruDeath: "3.3",
    finalVote: "4.4",
    patrickAwakening: "5.1",
  },
  slotPositionBlueprints: {
    "1.1": { meruru: "A12", karl: "A12", emily: "A12", fan: "A1", ziche: "A2", yamada: "A3", debora: "A4", anjie: "A5", patrick: "A6" },
    "1.2": { meruru: "A12", karl: "A12", emily: "A12", fan: "A12", ziche: "A12", yamada: "A12", debora: "A12", anjie: "A12", patrick: "A12" },
    "1.3": { meruru: "A19", karl: "A14", emily: "A12", fan: "A14", ziche: "A19", yamada: "A18", debora: "A19", anjie: "A17", patrick: "A18" },
    "1.4": { meruru: "A20", karl: "A20", emily: "A12", fan: "A12", ziche: "A14", yamada: "A18", debora: "A19", anjie: "A18", patrick: "A20" },
    "2.1": { meruru: "B3", karl: "A21", emily: "A20", fan: "A21", ziche: "A21", yamada: "A18", debora: "A19", anjie: "A21", patrick: "A22" },
    "2.2": { meruru: "B3", karl: "B3", emily: "B3", fan: "B3", ziche: "A20", yamada: "B3", debora: "B3", anjie: "B3", patrick: "B3" },
    "2.3": { meruru: "A19", karl: "A17", emily: "B3", fan: "A17", ziche: "A17", yamada: "A18", debora: "A17", anjie: "A17", patrick: "A17" },
    "2.4": { meruru: "A12", karl: "A12", emily: "A12", fan: "A12", ziche: "A12", yamada: "A12", debora: "A12", anjie: "A12", patrick: "A12" },
    "3.1": { meruru: "B2", karl: "B2", emily: "A12", fan: "B2", ziche: "B2", yamada: "A18", debora: "B2", anjie: "B2", patrick: "B2" },
    "3.2": { meruru: "B2", karl: "A20", emily: "B1", fan: "A20", ziche: "D6", yamada: "B1", debora: "B1", anjie: "B2", patrick: "D3" },
    "3.3": { meruru: "B2", karl: "B2", emily: "B2", fan: "B2", ziche: "B2", yamada: "B2", debora: "B2", anjie: "B2", patrick: "D3" },
    "3.4": { meruru: "B2", karl: "A13", emily: "B3", fan: "B3", ziche: "A13", yamada: "B3", debora: "B3", anjie: "A13", patrick: "B3" },
    "4.1": { meruru: "B2", karl: "A13", emily: "A13", fan: "A13", ziche: "A13", yamada: "A13", debora: "A13", anjie: "A13", patrick: "A13" },
    "4.2": { meruru: "B2", karl: "A13", emily: "A13", fan: "A13", ziche: "A13", yamada: "A13", debora: "A13", anjie: "A13", patrick: "A13" },
    "4.3": { meruru: "B2", karl: "A13", emily: "A13", fan: "A13", ziche: "A13", yamada: "A13", debora: "A13", anjie: "A13", patrick: "A13" },
    "4.4": { meruru: "B2", karl: "A13", emily: "A13", fan: "A13", ziche: "A13", yamada: "A13", debora: "A13", anjie: "A13", patrick: "A13" },
    "5.1": { meruru: "B2", karl: "D6", emily: "D3", fan: "D3", ziche: "D6", yamada: "D3", debora: "D6", anjie: "D3", patrick: "D4" },
    "5.2": { meruru: "B2", karl: "D6", emily: "D3", fan: "D6", ziche: "D6", yamada: "D3", debora: "D6", anjie: "D3", patrick: "D6" },
    "5.3": { meruru: "B2", karl: "D3", emily: "D3", fan: "D3", ziche: "D3", yamada: "D3", debora: "D3", anjie: "D3", patrick: "D3" },
    "5.4": { meruru: "B2", karl: "D3", emily: "D3", fan: "D3", ziche: "D3", yamada: "D3", debora: "D3", anjie: "D3", patrick: "D3" },
  },
};
